name: Auto Instrumental Music Generator

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Allow manual triggering for testing
    inputs:
      custom_theme:
        description: 'Optional uplifting theme (e.g., "ambient", "electronic", "peaceful") - only positive moods'
        required: false
        default: ''
      use_seed:
        description: 'Use a specific seed for reproducible generation (0-4294967295, or leave blank for random)'
        required: false
        default: ''

# Explicit permission scoping
permissions:
  contents: read
  issues: write
  actions: read

jobs:
  generate-instrumental-music-request:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Should complete quickly
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Make scripts executable
        run: |
          chmod +x .github/scripts/generate-music-workflow.sh
          chmod +x .github/scripts/generate-music-prompt.py
          chmod +x .github/scripts/create-api-request.py
          chmod +x .github/scripts/process-ai-response.py
          chmod +x .github/scripts/create-music-issue.js
      
      - name: Run instrumental music generation workflow
        env:
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          CUSTOM_THEME: ${{ github.event.inputs.custom_theme }}
          CUSTOM_SEED: ${{ github.event.inputs.use_seed }}
        run: |
          .github/scripts/generate-music-workflow.sh
      
      - name: Upload workflow logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: auto-instrumental-music-generator-logs-${{ github.run_number }}
          path: |
            auto_music_generator_*.log
            *.json
            *.txt
          retention-days: 7
 